services:
    tabby:
        image: tabbyml/tabby
        entrypoint: /opt/tabby/bin/tabby-cpu
        command: serve --model TabbyML/StarCoder-1B
        volumes:
            - "$HOME/.tabby:/data"
        ports:
            - 8080:8080
    sonarqube:
        image: sonarqube:latest
        ports:
            - 9000:9000
        networks:
            - sonarqube_net
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER_FILE: /run/secrets/postgres_user
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        secrets:
            - postgres_user
            - postgres_password
        networks:
            - postgres_net
    grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        networks:
            - postgres_net

networks:
    sonarqube_net:
        driver: bridge
    postgres_net:
        driver: bridge

secrets:
    postgres_user:
        file: ./secrets/postgres_user.txt
    postgres_password:
        file: ./secrets/postgres_password.txt