{
 "title": "TaskEvaluator Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Code Generation Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT code.\"Generator\", AVG(code.\"GenerationTimeMilliseconds\") as \"Average Generation Time in Milliseconds\"\r\nFROM \"DbCodeGenerationResult\" as code\r\nGROUP BY code.\"Generator\"\r\n"
    }
   ]
  },
  {
   "title": "Results per Try per Generator",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- Perfect\r\nSELECT\r\n  Concat(\r\n    invalidSyntax.\"Generator\",\r\n    ' - Attempt ',\r\n    invalidSyntax.\"RetryCount\" + 1\r\n  ) as \"Generator\",\r\n  perfect.\"count\" as \"Perfect\",\r\n  failedUnit.\"count\" as \"Failed Unit Test\",\r\n  invalidSyntax.\"count\" as \"Invalid Syntax\"\r\n  -- Failed Syntax\r\n  FROM (\r\n    SELECT\r\n      x.\"Generator\",\r\n      x.\"RetryCount\",\r\n      COUNT(x.\"Generator\")\r\n    FROM\r\n      (\r\n        SELECT\r\n          code.\"Generator\",\r\n          code.\"RetryCount\",\r\n          syn.\"SyntaxValid\",\r\n          unit.\"Failed Unit Tests\",\r\n          stat.\"Code Smells\"\r\n        FROM\r\n          \"DbCodeGenerationResult\" as code\r\n          LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  unit.\"CodeId\",\r\n                  COUNT(\r\n                    case\r\n                      res.\"Outcome\"\r\n                      when 0 then 1\r\n                      else null\r\n                    end\r\n                  ) as \"Failed Unit Tests\"\r\n                FROM\r\n                  \"DbUnitTestEvaluationResult\" as unit\r\n                  INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n                GROUP BY\r\n                  unit.\"CodeId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Failed Unit Tests\" > 0\r\n          ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  stat.\"CodeId\",\r\n                  COUNT(res.\"CodeAnalysisId\") as \"Code Smells\"\r\n                FROM\r\n                  \"DbStaticCodeAnalysisEvaluationResult\" as stat\r\n                  INNER JOIN \"DbStaticCodeAnalysisResult\" as res on stat.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  stat.\"Success\" is true\r\n                GROUP BY\r\n                  stat.\"CodeId\",\r\n                  res.\"CodeAnalysisId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Code Smells\" > 0\r\n          ) AS stat ON stat.\"CodeId\" = code.\"CodeId\"\r\n      ) as x\r\n    WHERE\r\n      x.\"SyntaxValid\" is false\r\n    GROUP BY\r\n      x.\"Generator\",\r\n      x.\"RetryCount\"\r\n  ) as invalidSyntax\r\nLEFT JOIN\r\n  (\r\n    SELECT\r\n      x.\"Generator\",\r\n      x.\"RetryCount\",\r\n      COUNT(x.\"Generator\")\r\n    FROM\r\n      (\r\n        SELECT\r\n          code.\"Generator\",\r\n          code.\"RetryCount\",\r\n          syn.\"SyntaxValid\",\r\n          unit.\"Failed Unit Tests\",\r\n          stat.\"Code Smells\"\r\n        FROM\r\n          \"DbCodeGenerationResult\" as code\r\n          LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  unit.\"CodeId\",\r\n                  COUNT(\r\n                    case\r\n                      res.\"Outcome\"\r\n                      when 0 then 1\r\n                      else null\r\n                    end\r\n                  ) as \"Failed Unit Tests\"\r\n                FROM\r\n                  \"DbUnitTestEvaluationResult\" as unit\r\n                  INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n                GROUP BY\r\n                  unit.\"CodeId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Failed Unit Tests\" > 0\r\n          ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  stat.\"CodeId\",\r\n                  COUNT(res.\"CodeAnalysisId\") as \"Code Smells\"\r\n                FROM\r\n                  \"DbStaticCodeAnalysisEvaluationResult\" as stat\r\n                  INNER JOIN \"DbStaticCodeAnalysisResult\" as res on stat.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  stat.\"Success\" is true\r\n                GROUP BY\r\n                  stat.\"CodeId\",\r\n                  res.\"CodeAnalysisId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Code Smells\" > 0\r\n          ) AS stat ON stat.\"CodeId\" = code.\"CodeId\"\r\n      ) as x\r\n    WHERE\r\n      x.\"SyntaxValid\" is true\r\n      and x.\"Failed Unit Tests\" is null\r\n      and x.\"Code Smells\" is null\r\n    GROUP BY\r\n      x.\"Generator\",\r\n      x.\"RetryCount\"\r\n  ) as perfect ON perfect.\"Generator\" = invalidSyntax.\"Generator\"\r\n  and perfect.\"RetryCount\" = invalidSyntax.\"RetryCount\"\r\n  -- Failed Unit Tests\r\n  LEFT JOIN (\r\n    SELECT\r\n      x.\"Generator\",\r\n      x.\"RetryCount\",\r\n      COUNT(x.\"Generator\")\r\n    FROM\r\n      (\r\n        SELECT\r\n          code.\"Generator\",\r\n          code.\"RetryCount\",\r\n          syn.\"SyntaxValid\",\r\n          unit.\"Failed Unit Tests\",\r\n          stat.\"Code Smells\"\r\n        FROM\r\n          \"DbCodeGenerationResult\" as code\r\n          LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  unit.\"CodeId\",\r\n                  COUNT(\r\n                    case\r\n                      res.\"Outcome\"\r\n                      when 0 then 1\r\n                      else null\r\n                    end\r\n                  ) as \"Failed Unit Tests\"\r\n                FROM\r\n                  \"DbUnitTestEvaluationResult\" as unit\r\n                  INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n                GROUP BY\r\n                  unit.\"CodeId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Failed Unit Tests\" > 0\r\n          ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  stat.\"CodeId\",\r\n                  COUNT(res.\"CodeAnalysisId\") as \"Code Smells\"\r\n                FROM\r\n                  \"DbStaticCodeAnalysisEvaluationResult\" as stat\r\n                  INNER JOIN \"DbStaticCodeAnalysisResult\" as res on stat.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  stat.\"Success\" is true\r\n                GROUP BY\r\n                  stat.\"CodeId\",\r\n                  res.\"CodeAnalysisId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Code Smells\" > 0\r\n          ) AS stat ON stat.\"CodeId\" = code.\"CodeId\"\r\n      ) as x\r\n    WHERE\r\n      x.\"SyntaxValid\" is true\r\n      and x.\"Failed Unit Tests\" is not null\r\n    GROUP BY\r\n      x.\"Generator\",\r\n      x.\"RetryCount\"\r\n  ) as failedUnit ON invalidSyntax.\"Generator\" = failedUnit.\"Generator\"\r\n  and invalidSyntax.\"RetryCount\" = failedUnit.\"RetryCount\"\r\nORDER BY\r\n  \"Generator\""
    }
   ]
  },
  {
   "title": "Results per Generator",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": " -- Perfect\r\nSELECT\r\n  perfect.\"Generator\",\r\n  perfect.\"count\" as \"Perfect\",\r\n  failedUnit.\"count\" as \"Failed Unit Test\",\r\n  invalidSyntax.\"count\" as \"Invalid Syntax\"\r\nFROM\r\n  (\r\n    SELECT\r\n      x.\"Generator\",\r\n      COUNT(x.\"Generator\")\r\n    FROM\r\n      (\r\n        SELECT\r\n          code.\"Generator\",\r\n          syn.\"Invalid Syntax\",\r\n          unit.\"Failed Unit Tests\",\r\n          stat.\"Code Smells\"\r\n        FROM\r\n          (\r\n            SELECT\r\n              code.\"Generator\",\r\n              code.\"CodeId\"\r\n            FROM\r\n              \"DbCodeGenerationResult\" as code\r\n              INNER JOIN (\r\n                SELECT\r\n                  code.\"TaskId\",\r\n                  code.\"Generator\",\r\n                  MAX(code.\"RetryCount\") as \"RetryCount\"\r\n                FROM\r\n                  \"DbCodeGenerationResult\" as code\r\n                GROUP BY\r\n                  code.\"TaskId\",\r\n                  code.\"Generator\"\r\n                ORDER BY\r\n                  code.\"TaskId\"\r\n              ) as rc ON rc.\"TaskId\" = code.\"TaskId\"\r\n              and rc.\"Generator\" = code.\"Generator\"\r\n              and rc.\"RetryCount\" = code.\"RetryCount\"\r\n          ) as code\r\n          LEFT JOIN (\r\n            SELECT\r\n              syn.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  syn.\"SyntaxValid\"\r\n                  when false then 1\r\n                  else null\r\n                end\r\n              ) as \"Invalid Syntax\"\r\n            FROM\r\n              \"DbSyntaxValidationResult\" as syn\r\n            GROUP BY\r\n              syn.\"CodeId\"\r\n          ) AS syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  unit.\"CodeId\",\r\n                  COUNT(\r\n                    case\r\n                      res.\"Outcome\"\r\n                      when 0 then 1\r\n                      else null\r\n                    end\r\n                  ) as \"Failed Unit Tests\"\r\n                FROM\r\n                  \"DbUnitTestEvaluationResult\" as unit\r\n                  INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n                GROUP BY\r\n                  unit.\"CodeId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Failed Unit Tests\" > 0\r\n          ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  stat.\"CodeId\",\r\n                  COUNT(res.\"CodeAnalysisId\") as \"Code Smells\"\r\n                FROM\r\n                  \"DbStaticCodeAnalysisEvaluationResult\" as stat\r\n                  INNER JOIN \"DbStaticCodeAnalysisResult\" as res on stat.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  stat.\"Success\" is true\r\n                GROUP BY\r\n                  stat.\"CodeId\",\r\n                  res.\"CodeAnalysisId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Code Smells\" > 0\r\n          ) AS stat ON stat.\"CodeId\" = code.\"CodeId\"\r\n      ) as x\r\n    WHERE\r\n      x.\"Invalid Syntax\" = 0\r\n      and x.\"Failed Unit Tests\" is null\r\n      and x.\"Code Smells\" is null\r\n    GROUP BY\r\n      x.\"Generator\"\r\n  ) as perfect\r\n  -- Failed Syntax\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      COUNT(code.\"Generator\")\r\n    FROM\r\n      (\r\n        -- Get last retry\r\n        SELECT\r\n          code.\"Generator\",\r\n          code.\"CodeId\"\r\n        FROM\r\n          \"DbCodeGenerationResult\" as code\r\n          INNER JOIN (\r\n            SELECT\r\n              code.\"TaskId\",\r\n              code.\"Generator\",\r\n              MAX(code.\"RetryCount\") as \"RetryCount\"\r\n            FROM\r\n              \"DbCodeGenerationResult\" as code\r\n            GROUP BY\r\n              code.\"TaskId\",\r\n              code.\"Generator\"\r\n            ORDER BY\r\n              code.\"TaskId\"\r\n          ) as rc ON rc.\"TaskId\" = code.\"TaskId\"\r\n          and rc.\"Generator\" = code.\"Generator\"\r\n          and rc.\"RetryCount\" = code.\"RetryCount\"\r\n      ) as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" AS syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n    WHERE\r\n      syn.\"SyntaxValid\" is false\r\n    GROUP BY\r\n      code.\"Generator\"\r\n  ) as invalidSyntax ON perfect.\"Generator\" = invalidSyntax.\"Generator\"\r\n  -- Failed Unit Tests\r\n  LEFT JOIN (\r\n    SELECT\r\n      x.\"Generator\",\r\n      COUNT(x.\"Generator\")\r\n    FROM\r\n      (\r\n        SELECT\r\n          code.\"Generator\",\r\n          syn.\"Invalid Syntax\",\r\n          unit.\"Failed Unit Tests\",\r\n          stat.\"Code Smells\"\r\n        FROM\r\n          (\r\n            -- Get last retry\r\n            SELECT\r\n              code.\"Generator\",\r\n              code.\"CodeId\"\r\n            FROM\r\n              \"DbCodeGenerationResult\" as code\r\n              INNER JOIN (\r\n                SELECT\r\n                  code.\"TaskId\",\r\n                  code.\"Generator\",\r\n                  MAX(code.\"RetryCount\") as \"RetryCount\"\r\n                FROM\r\n                  \"DbCodeGenerationResult\" as code\r\n                GROUP BY\r\n                  code.\"TaskId\",\r\n                  code.\"Generator\"\r\n                ORDER BY\r\n                  code.\"TaskId\"\r\n              ) as rc ON rc.\"TaskId\" = code.\"TaskId\"\r\n              and rc.\"Generator\" = code.\"Generator\"\r\n              and rc.\"RetryCount\" = code.\"RetryCount\"\r\n          ) as code\r\n          LEFT JOIN (\r\n            SELECT\r\n              syn.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  syn.\"SyntaxValid\"\r\n                  when false then 1\r\n                  else null\r\n                end\r\n              ) as \"Invalid Syntax\"\r\n            FROM\r\n              \"DbSyntaxValidationResult\" as syn\r\n            GROUP BY\r\n              syn.\"CodeId\"\r\n          ) AS syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  unit.\"CodeId\",\r\n                  COUNT(\r\n                    case\r\n                      res.\"Outcome\"\r\n                      when 0 then 1\r\n                      else null\r\n                    end\r\n                  ) as \"Failed Unit Tests\"\r\n                FROM\r\n                  \"DbUnitTestEvaluationResult\" as unit\r\n                  INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n                GROUP BY\r\n                  unit.\"CodeId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Failed Unit Tests\" > 0\r\n          ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n          LEFT JOIN (\r\n            SELECT\r\n              *\r\n            FROM\r\n              (\r\n                SELECT\r\n                  stat.\"CodeId\",\r\n                  COUNT(res.\"CodeAnalysisId\") as \"Code Smells\"\r\n                FROM\r\n                  \"DbStaticCodeAnalysisEvaluationResult\" as stat\r\n                  INNER JOIN \"DbStaticCodeAnalysisResult\" as res on stat.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  stat.\"Success\" is true\r\n                GROUP BY\r\n                  stat.\"CodeId\",\r\n                  res.\"CodeAnalysisId\"\r\n              ) as results\r\n            WHERE\r\n              results.\"Code Smells\" > 0\r\n          ) AS stat ON stat.\"CodeId\" = code.\"CodeId\"\r\n      ) as x\r\n    WHERE\r\n      x.\"Invalid Syntax\" = 0\r\n      and x.\"Failed Unit Tests\" is not null\r\n    GROUP BY\r\n      x.\"Generator\"\r\n  ) as failedUnit ON perfect.\"Generator\" = failedUnit.\"Generator\""
    }
   ]
  },
  {
   "title": "Percentage of passing Unit Tests per Generator",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  code.\"Generator\",\r\n  SUM(results.\"Passed\") / (SUM(results.\"Passed\") + SUM(results.\"Failed\")) as \"Passed\",\r\n  SUM(results.\"Failed\") / (SUM(results.\"Passed\") + SUM(results.\"Failed\")) as \"Failed\"\r\nFROM\r\n  (\r\n    -- Last Retry\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"CodeId\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      INNER JOIN (\r\n        SELECT\r\n          code.\"TaskId\",\r\n          code.\"Generator\",\r\n          MAX(code.\"RetryCount\") as \"RetryCount\"\r\n        FROM\r\n          \"DbCodeGenerationResult\" as code\r\n          LEFT JOIN \"DbSyntaxValidationResult\" as syn on syn.\"CodeId\" = code.\"CodeId\"\r\n        WHERE\r\n          syn.\"SyntaxValid\" is true\r\n        GROUP BY\r\n          code.\"TaskId\",\r\n          code.\"Generator\"\r\n        ORDER BY\r\n          code.\"TaskId\"\r\n      ) as rc ON rc.\"TaskId\" = code.\"TaskId\"\r\n      and rc.\"Generator\" = code.\"Generator\"\r\n      and rc.\"RetryCount\" = code.\"RetryCount\"\r\n  ) as code\r\n  LEFT JOIN (\r\n    SELECT\r\n      unit.\"CodeId\",\r\n      COUNT(\r\n        case\r\n          res.\"Outcome\"\r\n          when 1 then 1\r\n          else null\r\n        end\r\n      ) as \"Passed\",\r\n      COUNT(\r\n        case\r\n          res.\"Outcome\"\r\n          when 0 then 1\r\n          else null\r\n        end\r\n      ) as \"Failed\"\r\n    FROM\r\n      \"DbUnitTestEvaluationResult\" as unit\r\n      INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n    GROUP BY\r\n      unit.\"CodeId\"\r\n  ) as results ON results.\"CodeId\" = code.\"CodeId\"\r\nGROUP BY\r\n  code.\"Generator\"\r\nORDER BY\r\n  code.\"Generator\""
    }
   ]
  },
  {
   "title": "Retry ineffectiveness",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Syntax not improved\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\"\r\n    FROM\r\n    \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and x.\"SyntaxValid\" is false\r\n  and y.\"SyntaxValid\" is false\r\nGROUP BY\r\n  x.\"Generator\"\r\n"
    },
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Syntax invalid after syntax was valid\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\"\r\n    FROM\r\n    \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and x.\"SyntaxValid\" is false\r\n  and y.\"SyntaxValid\" is true\r\nGROUP BY\r\n  x.\"Generator\""
    },
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Unit test not improved\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and x.\"SyntaxValid\" is true\r\n  and y.\"SyntaxValid\" is true\r\n  and x.\"Failed Unit Tests\" = y.\"Failed Unit Tests\"\r\nGROUP BY\r\n  x.\"Generator\""
    },
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Unit test worse\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and x.\"SyntaxValid\" is true\r\n  and y.\"SyntaxValid\" is true\r\n  and x.\"Failed Unit Tests\" > y.\"Failed Unit Tests\"\r\nGROUP BY\r\n  x.\"Generator\"\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Retry effectiveness",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Syntax invalid to perfect\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and y.\"SyntaxValid\" is false\r\n  and x.\"SyntaxValid\" is true\r\n  and x.\"Failed Unit Tests\" is null\r\nGROUP BY\r\n  x.\"Generator\""
    },
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Syntax invalid to valid but not perfect\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and y.\"SyntaxValid\" is false\r\n  and x.\"SyntaxValid\" is true\r\n  and x.\"Failed Unit Tests\" > 0\r\nGROUP BY\r\n  x.\"Generator\""
    },
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Unit test failed to perfect\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and y.\"SyntaxValid\" is true\r\n  and y.\"Failed Unit Tests\" > 0\r\n  and x.\"SyntaxValid\" is true\r\n  and x.\"Failed Unit Tests\" is null\r\nGROUP BY\r\n  x.\"Generator\""
    },
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  COUNT(*) as \"Unit test improved\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as x\r\n  LEFT JOIN (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      code.\"CodeId\",\r\n      code.\"RetryCount\",\r\n      syn.\"SyntaxValid\",\r\n      unit.\"Failed Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n      LEFT JOIN (\r\n        SELECT\r\n          *\r\n        FROM\r\n          (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n                WHERE\r\n                  unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results\r\n        WHERE\r\n          results.\"Failed Unit Tests\" > 0\r\n      ) AS unit ON unit.\"CodeId\" = code.\"CodeId\"\r\n  ) as y on x.\"TaskId\" = y.\"TaskId\"\r\n  and x.\"Generator\" = y.\"Generator\"\r\nWHERE\r\n  x.\"RetryCount\" - y.\"RetryCount\" = 1\r\n  and y.\"SyntaxValid\" is true\r\n  and x.\"SyntaxValid\" is true\r\n  and y.\"Failed Unit Tests\" - x.\"Failed Unit Tests\" > 0\r\nGROUP BY\r\n  x.\"Generator\""
    }
   ]
  },
  {
   "title": "Average Line Count per Generator",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.\"Generator\",\r\n  AVG(LENGTH(c.\"GeneratedPart\") - LENGTH(REPLACE(c.\"GeneratedPart\", E'\\n', '')) + 1) as \"Average Line Count\"\r\n  \r\nFROM\r\n  \"DbCodeGenerationResult\" c\r\n  LEFT JOIN \"DbSyntaxValidationResult\" syn on syn.\"CodeId\" = c.\"CodeId\"\r\n  LEFT JOIN (\r\n    SELECT\r\n      *\r\n    FROM\r\n      (\r\n        SELECT\r\n          unit.\"CodeId\",\r\n          COUNT(\r\n            case\r\n              res.\"Outcome\"\r\n              when 0 then 1\r\n              else null\r\n            end\r\n          ) as \"Failed Unit Tests\"\r\n        FROM\r\n          \"DbUnitTestEvaluationResult\" as unit\r\n          INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n        WHERE\r\n          unit.\"Success\" is true\r\n        GROUP BY\r\n          unit.\"CodeId\"\r\n      ) as results\r\n  ) AS unit ON unit.\"CodeId\" = c.\"CodeId\"\r\nWHERE\r\n  syn.\"SyntaxValid\" is true\r\n  and unit.\"Failed Unit Tests\" = 0\r\nGROUP BY\r\n  c.\"Generator\""
    }
   ]
  },
  {
   "title": "Tries until",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  1 + AVG(x.\"First Try with Valid Syntax\") as \"Tries until Syntax is valid\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      MIN(code.\"RetryCount\") as \"First Try with Valid Syntax\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" as code\r\n      LEFT JOIN \"DbSyntaxValidationResult\" as syn ON syn.\"CodeId\" = code.\"CodeId\"\r\n    WHERE\r\n      syn.\"SyntaxValid\" is true or code.\"RetryCount\" = 2\r\n    GROUP BY\r\n      code.\"Generator\",\r\n      code.\"TaskId\"\r\n  ) as x\r\nGROUP BY\r\n  x.\"Generator\"\r\nORDER BY\r\n  x.\"Generator\"\r\n"
    },
    {
     "rawSql": "SELECT\r\n  x.\"Generator\",\r\n  1 + AVG(x.\"First Try with No Failing Unit Tests\") as \"Tries until Unit Tests pass\"\r\nFROM\r\n  (\r\n    SELECT\r\n      code.\"Generator\",\r\n      code.\"TaskId\",\r\n      MAX(code.\"RetryCount\") as \"First Try with No Failing Unit Tests\"\r\n    FROM\r\n      \"DbCodeGenerationResult\" code\r\n      LEFT JOIN (\r\n        SELECT\r\n          code.\"Generator\",\r\n          code.\"TaskId\"\r\n        FROM\r\n          \"DbCodeGenerationResult\" as code\r\n          LEFT JOIN (\r\n            SELECT\r\n              unit.\"CodeId\",\r\n              COUNT(\r\n                case\r\n                  res.\"Outcome\"\r\n                  when 0 then 1\r\n                  else null\r\n                end\r\n              ) as \"Failed Unit Tests\"\r\n            FROM\r\n              \"DbUnitTestEvaluationResult\" as unit\r\n              INNER JOIN \"DbUnitTestResult\" as res on unit.\"CodeId\" = res.\"CodeId\"\r\n            WHERE\r\n              unit.\"Success\" is true\r\n            GROUP BY\r\n              unit.\"CodeId\"\r\n          ) as results on results.\"CodeId\" = code.\"CodeId\"\r\n        WHERE\r\n          results.\"Failed Unit Tests\" = 0\r\n        GROUP BY\r\n          code.\"Generator\",\r\n          code.\"TaskId\"\r\n      ) as y on y.\"TaskId\" = code.\"TaskId\"\r\n      and y.\"Generator\" = code.\"Generator\"\r\n    GROUP BY\r\n      code.\"Generator\",\r\n      code.\"TaskId\"\r\n  ) as x\r\nGROUP BY\r\n  x.\"Generator\"\r\nORDER BY\r\n  x.\"Generator\""
    }
   ]
  },
  {
   "title": "Syntax Validity Rate per Try",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 7, "x": 16, "y": 21 },
   "targets": [
    {
     "rawSql": "-- Syntax invalid for reach try, per generator\r\nSELECT\r\n  code.\"Generator\",\r\n  code.\"RetryCount\" + 1 as \"Try\",\r\n  SUM(results.\"Valid\") / (SUM(results.\"Valid\") + SUM(results.\"Invalid\")) as \"Valid\"\r\nFROM\r\n  \"DbCodeGenerationResult\" as code\r\n  INNER JOIN (\r\n    SELECT\r\n      syn.\"CodeId\",\r\n      COUNT(\r\n        case\r\n          syn.\"SyntaxValid\"\r\n          when true then 1\r\n          else null\r\n        end\r\n      ) as \"Valid\",\r\n      COUNT(\r\n        case\r\n          syn.\"SyntaxValid\"\r\n          when false then 1\r\n          else null\r\n        end\r\n      ) as \"Invalid\"\r\n    FROM\r\n      \"DbSyntaxValidationResult\" as syn\r\n    GROUP BY\r\n      syn.\"CodeId\"\r\n  ) AS results ON results.\"CodeId\" = code.\"CodeId\"\r\n  WHERE code.\"Generator\" = 'GitHub Copilot'\r\nGROUP BY\r\n  code.\"Generator\",\r\n  code.\"RetryCount\"\r\nORDER BY\r\n  code.\"Generator\",\r\n  code.\"RetryCount\""
    },
    {
     "rawSql": "-- Syntax invalid for reach try, per generator\r\nSELECT\r\n  code.\"Generator\",\r\n  code.\"RetryCount\" + 1 as \"Try\",\r\n  SUM(results.\"Valid\") / (SUM(results.\"Valid\") + SUM(results.\"Invalid\")) as \"Valid\"\r\nFROM\r\n  \"DbCodeGenerationResult\" as code\r\n  INNER JOIN (\r\n    SELECT\r\n      syn.\"CodeId\",\r\n      COUNT(\r\n        case\r\n          syn.\"SyntaxValid\"\r\n          when true then 1\r\n          else null\r\n        end\r\n      ) as \"Valid\",\r\n      COUNT(\r\n        case\r\n          syn.\"SyntaxValid\"\r\n          when false then 1\r\n          else null\r\n        end\r\n      ) as \"Invalid\"\r\n    FROM\r\n      \"DbSyntaxValidationResult\" as syn\r\n    GROUP BY\r\n      syn.\"CodeId\"\r\n  ) AS results ON results.\"CodeId\" = code.\"CodeId\"\r\n  WHERE code.\"Generator\" = 'Tabby'\r\nGROUP BY\r\n  code.\"Generator\",\r\n  code.\"RetryCount\"\r\nORDER BY\r\n  code.\"Generator\",\r\n  code.\"RetryCount\""
    }
   ]
  }
 ]
}